spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/book_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效


server:
  port: 8081

mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.example.book.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql